### ISSUE TITLE
Some Q about counterfact dataset result

### ISSUE THREAD

**Issue by caiyuchen-ustc** [evandez/REMEDI#2]
Hello，Dear author:
  I recently came across your article, and I'm really excited about it. However, there are two questions that have been bothering me, and I would appreciate it if the author could provide some answers.
Question 1:
  In the Counterfact dataset, the author mentioned in the paper that using the sum of KL divergences helps prevent model degradation. However, in the code, it appears that the KL divergence is only constrained between the last token of each sentence.
Question 2：
  It seems that the author has used a different generation approach compared to ROME, resulting in lower Fluency (Fl.) and Consistency (Cons.) scores.

**Comment by evandez** [comment]
Thanks for opening this--happy to answer any questions!

Q1: The KL term is over all non-entity tokens in the prompt. However, this term is zero for all tokens before the entity, since we're working with causal language models. So it's really all tokens between the entity and (not including) the last token of the prompt. You can see the code for this [here](https://github.com/evandez/REMEDI/blob/main/remedi/editors.py#L382).

Q2: Could you please elaborate on why you think it's different? The intention was to do it in exactly the same way, but it's possible I missed something.

**Comment by caiyuchen-ustc** [comment]
Dear author,
Q1. I apologize for my previous misstatement. In the code, it seems that the KL divergence only constrains the KL divergence of the last sentence in each batch, rather than all sentences. This can be observed specifically in lines 396 and 399 of the code in "Editor“.
Q2. In ROME, Meng et al. defined a function called "generate_fast" for generating sentences and used top-k sampling to ensure fluency. In this code, the author is using "model.generate(**inputs, **generate_kwargs)" with "do_sample=False", which leads to low Fluency and Consistency scores for the generated sentences. I attempted to re-adjust the parameters of model.generate and found that the Fluency score exceeded 600 (in Prefix and Replace).
