### ISSUE TITLE
neighborhood scores?

### ISSUE THREAD

**Issue by ENSCMA2** [evandez/REMEDI#5]
Hi! The paper mentions that REMEDI was also evaluated on the "neighborhood" benchmark for CounterFact, but I seem to only see  "efficacy", "paraphrase", "generation", and "essence" as the supported benchmarks. How would one go about reproducing the neighborhood scores as in Table 3 of the paper?

**Comment by evandez** [comment]
That's right, there is no neighborhood score code in this repo.

For ROME/FT, we computed it using the ROME code: https://github.com/kmeng01/rome/blob/main/experiments/py/eval_utils_counterfact.py#L74

For REMEDI/prompting methods, we didn't explicitly compute it because they do not touch neighboring prompts :) 

Hope this helps!
